name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-214.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  marquee_list: ^1.0.0
  rive: ^0.13.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true
  assets:

    - assets/images/  
    - assets/icons/ 
    - assets/gradients/backgroundgif.riv
  fonts:
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
        - asset: fonts/JosefinSans-SemiBold.ttf
    - family: Jost
      fonts:
        - asset: fonts/Jost-Bold.ttf
        - asset: fonts/Jost-Medium.ttf
        - asset: fonts/Jost-Regular.ttf  
    
